In [2]:
import numpy as np
import sys

In [29]:
SIZE = range(1000)
print(sys.getsizeof(5)*len(SIZE))

28000


In [34]:
len(SIZE)

1000

In [36]:
a = np.arange(1000)
4*a.itemsize

16

In [25]:
a.size


1000

In [9]:
l = range(1000)

In [10]:
l

range(0, 1000)

In [11]:
l.length


AttributeError: 'range' object has no attribute 'length'

In [9]:
a = np.array([[1,3],[3,5],[5,6]], dtype=complex)
a

array([[1.+0.j, 3.+0.j],
       [3.+0.j, 5.+0.j],
       [5.+0.j, 6.+0.j]])

# Zeros

In [11]:
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# Ones

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
l = range(5)

In [25]:
np.arange(1,6,4)

array([1, 5])

# linspace

In [29]:
np.linspace(1,5,20, endpoint=False, retstep=True)

(array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
        3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8]),
 0.2)

# Reshape

In [35]:
a = np.array([[1,3],[3,5],[5,6]], dtype=complex)
a


array([[1.+0.j, 3.+0.j],
       [3.+0.j, 5.+0.j],
       [5.+0.j, 6.+0.j]])

In [34]:
a.reshape(2,3)

array([[1.+0.j, 3.+0.j, 3.+0.j],
       [5.+0.j, 5.+0.j, 6.+0.j]])

# Ravel flatten array to one dimensional

In [38]:
a = np.array([[1,3],[3,5],[5,6]], dtype=int)
a.ravel()

array([1, 3, 3, 5, 5, 6])

# min max sum

In [40]:
a.min()

1

In [41]:
a.max()

6

In [42]:
a.sum()

23

In [44]:
a


array([[1, 3],
       [3, 5],
       [5, 6]])

# sum with axis o to add column and 1 to add row

In [45]:
a.sum(axis=0)

array([ 9, 14])

In [46]:
a.sum(axis=1)

array([ 4,  8, 11])

In [47]:
np.sqrt(a)

array([[1.        , 1.73205081],
       [1.73205081, 2.23606798],
       [2.23606798, 2.44948974]])

In [54]:
np.std(a)


1.674979270186815

In [55]:
a




array([[1, 3],
       [3, 5],
       [5, 6]])

In [69]:
B = np.array([[1,3],[4,5]])
c= np.array([[2,3],[6,5]])


B

array([[1, 3],
       [4, 5]])

In [70]:
c

array([[2, 3],
       [6, 5]])

In [71]:
B*c

array([[ 2,  9],
       [24, 25]])

In [59]:
np.std(B)

1.4142135623730951

In [60]:
np.sqrt(2)

1.4142135623730951