In [1]:
import numpy as np

# np.loadtxt() vs np.genfromtxt()

#### Load implies data is ready to be directly imported and used

##### generate indicate that the function creates dataset from the text file generating requires constructing the array as we go through the text file

In [7]:
lending_co_data_numeric_1 = np.loadtxt("Lending-Company-Numeric-Data.csv", delimiter = ',')
lending_co_data_numeric_1

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [9]:
lending_co_data_numeric_2 = np.genfromtxt("Lending-Company-Numeric-Data.csv", delimiter = ',')
lending_co_data_numeric_2

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [10]:
np.array_equal(lending_co_data_numeric_1,lending_co_data_numeric_2)

True

In [17]:
lending_co_data_numeric_NAN = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter = ';')
lending_co_data_numeric_NAN

TypeError: 'delimiter' is an invalid keyword argument for str()

In [44]:
lending_co_data_numeric_NAN = np.loadtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter = ';', dtype= np.str)
lending_co_data_numeric_NAN

C:\Users\buraj\AppData\Local\Temp\ipykernel_7884\1519435549.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  lending_co_data_numeric_NAN = np.loadtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter = ';', dtype= np.str)


array([['2000', '40', '365', '3121', '4241', '13621'],
       ['2000', '40', '365', '3061', '4171', '15041'],
       ['1000', '40', '365', '2160', '3280', '15340'],
       ...,
       ['', '40', '365', '4201', '5001', '16600'],
       ['1000', '40', '365', '2080', '3320', '15600'],
       ['2000', '40', '365', '4601', '4601', '16600']], dtype='<U5')

# Partial Cleaning While Importing

In [20]:
lending_co_data_numeric_NAN = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter = ';')
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

### Used to remove comment that might be in csv file by removing that line from Top

In [21]:
lending_co_data_numeric_NAN = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter = ';', skip_header = 1)
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

### Used to remove comment that might be in csv file by removing that line from Bottom

In [26]:
lending_co_data_numeric_NAN = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter = ';', skip_footer = 3 )
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    nan,   365.,  3081.,  4341., 16600.],
       [ 2000.,    40.,   365.,  3401.,    nan, 16600.],
       [ 2000.,    40.,   365.,    nan,  5440., 16600.]])

### Used to remove comment that might be in csv file by removing that line from Columns

In [31]:
lending_co_data_numeric_NAN = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter = ';', usecols = (0,1,3))
lending_co_data_numeric_NAN

array([[2000.,   40., 3121.],
       [2000.,   40., 3061.],
       [1000.,   40., 2160.],
       ...,
       [  nan,   40., 4201.],
       [1000.,   40., 2080.],
       [2000.,   40., 4601.]])

### Combining skip header and use cols together

In [32]:
lending_co_data_numeric_NAN = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter = ';', usecols = (0,1,3), skip_header = 2, skip_footer = 2)
lending_co_data_numeric_NAN

array([[1000.,   40., 2160.],
       [2000.,   40., 3041.],
       [2000.,   50., 3470.],
       ...,
       [2000.,   40., 3401.],
       [2000.,   40.,   nan],
       [  nan,   40., 4201.]])

In [33]:
a,b,v = 1,2,3

In [34]:
a

1

In [35]:
b

2

In [36]:
v

3

### Loading single value to three variable

In [38]:
a,b,c  = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter = ';', usecols = (0,1,3), skip_header = 2, skip_footer = 2, unpack = True)
a,b,c

(array([1000., 2000., 2000., ..., 2000., 2000.,   nan]),
 array([40., 40., 50., ..., 40., 40., 40.]),
 array([2160., 3041., 3470., ..., 3401.,   nan, 4201.]))

### indexing using index_col


In [47]:
import pandas as pd


In [50]:
pd.read_csv('Lending-company.csv', index_col="LoanID" )

StringID    Product CustomerGender     Location    Region  \
LoanID                                                                 
1          LoanID_1  Product B         Female   Location 3  Region 2   
2          LoanID_2  Product D         Female   Location 6  Region 6   
3          LoanID_3  Product B           Male   Location 8  Region 3   
4          LoanID_4  Product A           Male  Location 26  Region 2   
5          LoanID_5  Product B         Female  Location 34  Region 3   
...             ...        ...            ...          ...       ...   
1039    LoanID_1039  Product B           Male  Location 73  Region 6   
1040    LoanID_1040  Product A           Male  Location 82  Region 1   
1041    LoanID_1041  Product A   NotSpecified  Location 11  Region 4   
1042    LoanID_1042  Product B         Female  Location 26  Region 6   
1043    LoanID_1043  Product A   NotSpecified  Location 94  Region 6   

        TotalPrice   StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  \
LoanID                                                                       
1          17600.0  04/07/2018     2200         45          365       3221   
2              NaN  02/01/2019     2200         45          365       3161   
3          16600.0  08/12/2016     1000         45          365       2260   
4          17600.0         NaN     2200         45          365       3141   
5          21250.0  28/10/2017     2200         55          365       3570   
...            ...         ...      ...        ...          ...        ...   
1039       17300.0  29/12/2018     2200         45          365       3251   
1040           NaN  28/03/2018     2200         45          365       4090   
1041       17300.0  26/04/2018     2200         45          365       4051   
1042       16300.0  25/10/2016     1000         45          365       1930   
1043       17300.0  15/05/2019     2200         45          365       4451   

        AmtPaid60  AmtPaid360        LoanStatus  
LoanID                                           
1            4166       14621            Active  
2            4096       16041            Active  
3            3205       16340               NaN  
4            4166       16321            Active  
5            4745       14720            Active  
...           ...         ...               ...  
1039         4743       16617  Finished Payment  
1040         5582       16617  Finished Payment  
1041         5143       16617  Finished Payment  
1042         3462       15617  Finished Payment  
1043         4743       16617  Finished Payment  

[1043 rows x 14 columns]

In [ ]:
new_csv_data = pd.read_json('Leading-company.json')
